[tool.poetry]
name = "db-sql"
version = "0.1.0"
description = ""
authors = ["timur <timurka.t.r@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
sqlalchemy = "^2.0.23"
alembic = "^1.13.0"
asyncpg = "^0.29.0"
psycopg2 = "^2.9.9"
psycopg2-binary = "^2.9.9"
fastapi = {extras = ["all"], version = "^0.105.0"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
