"""code_rework_second

Revision ID: 152c37b604bb
Revises: 48ac879d8fab
Create Date: 2023-12-20 18:54:11.347271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '152c37b604bb'
down_revision: Union[str, None] = '48ac879d8fab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('street', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'street')
    # ### end Alembic commands ###
