"""code_rework

Revision ID: 48ac879d8fab
Revises: 0128af4aa59a
Create Date: 2023-12-20 18:49:24.463982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48ac879d8fab'
down_revision: Union[str, None] = '0128af4aa59a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('address', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_address_country'), 'address', ['country'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_address_country'), table_name='address')
    op.alter_column('address', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
