"""fix-2

Revision ID: 88bce353c0ea
Revises: 7a38c17d8c2b
Create Date: 2024-02-22 20:18:56.722120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88bce353c0ea'
down_revision: Union[str, None] = '7a38c17d8c2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'deleted_at')
    # ### end Alembic commands ###
